namespace RabbitMQConnector
{
    public class PricingDataManagerTest
    {
        public static string Create1()
        {
            return "<request>" +
                        "<recordset>" +
                                "<elementid>Cabanas-C1</elementid>" +
                                "<metadata baseTime=\"2015-01-14T12:00:00.000+01:00\" creationTime=\"2015-01-14T12:00:00.000+01:00\" generatedBy=\"APS\" comment=\"generated by FER\" />" +
                                "<record>" +
                                    "<from>2015-01-14T12:00:00+01:00</from>" +
                                    "<to>2015-01-14T13:00:00+01:00</to>" +
                                    "<variable name=\"price\">" +
                                        "<value>1.23</value>" +
                                    "</variable>" +
                                "</record>" +
                                "<record>" +
                                    "<from>2015-01-14T13:00:00+01:00</from>" +
                                    "<to>2015-01-14T14:00:00+01:00</to>" +
                                    "<variable name=\"price\">" +
                                        "<value>2.34</value>" +
                                    "</variable>" +
                                "</record>" +
                        "</recordset>" +
                      "</request>";
        }

        public static string Read()
        {
            return "<request>" +
	"<query>" +
		"<elementId>Cabanas-C1</elementId> //Dma id" +
		"<start>2015-01-14T00:00:00.000+01:00</start>" +
		"<end>2015-01-16T00:00:00.000+01:00</end>" +
		"<simulation>2015-01-16T00:00:00.000+01:00</simulation>" +
		"<timeStep>3600</timeStep>" +
"</query>" +
"</request>";
        }
    }
}
